### ISSUE TITLE
Document non-obvious clip/no-alpha interaction

### ISSUE THREAD

**Issue by AlanDeSmet** [jaames/playdate-reverse-engineering#12]
Having spent too long debugging this, I think the pdi/pdt documentation should add some notes on interpreting the cell header. Here's my immediate thoughts (feel free to use them if you think they're useful):

> When compiling images, the Playdate software tries to eliminate borders that are entirely transparent. How many rows or columns were removed are the clip values. If the clipped image has no remaining transparent pixels, no alpha channel will be written at all.
>
> As a result, an image with transparent pixels may not have an alpha channel. The pixels for which there is data are opaque. When the clipped borders are re-added, they are always transparent.

**Comment by jaames** [comment]
Ah, yeah, probably a good shout. I'll think about the wording a bit, maybe it could be clearer with an illustration too

**Comment by jaames** [comment]
Updated the .pdi documentation to make this more obvious - thanks!
