### ISSUE TITLE
API pagination?

### ISSUE THREAD

**Issue by tungol** [jaames/playdate-reverse-engineering#19]
The catalog API returns a consistent 50 results, so I suspect there must be a way to go to the next page of results. I tried a couple likely options with no luck. If you have any clues in that direction, I'd appreciate it.

**Comment by tungol** [comment]
To answer my own question: I think the catalog API documented is a legacy one. The current endpoint is `/games/groups/catalog/` and no pagination is required.

**Comment by gatesphere** [comment]
As of this moment, there is a paginated API available at:

`/games/paged/catalog/?page=N`

Where `N` is an integer starting at 1.  This returns a `next` parameter with the API link to the next page of results, or `none` if you're on the last page.
