### ISSUE TITLE
Any tools to decompile .luac files?

### ISSUE THREAD

**Issue by gregsadetsky** [jaames/playdate-reverse-engineering#5]
Thanks for this list of tools!

Would you be able to recommend tools that work on macos and allow decompiling / disassembling of .luac files?

Thanks!

**Comment by jaames** [comment]
Hey! I had some flakey success using unluac with these patches by zhuowei:
https://gist.github.com/zhuowei/56ffdda8913d603bf99b874d4be33984

However, Panic has since changed the Lua version shipped with more recent versions of the firmware and SDK, so your mileage may vary

**Comment by gregsadetsky** [comment]
Thanks for the quick response!

**Comment by jaames** [comment]
No worries! I should say, I haven't spent a whole lot of time trying to decompile Playdate Lua yet (compilers and decompilers are... not my forté), so if you find something that works well please give me a shout!

I'll also make a note to reply to this thread if I ever take a deeper look into it.

**Comment by scratchminer** [comment]
I patched the Java applicaton `unluac` to decompile *all* known Lua bytecode files, including the ones with a standard Lua 5.4 header (and, as it turns out, opcodes appended to the end of the ORDER OP enum):
[https://github.com/scratchminer/unluac](https://github.com/scratchminer/unluac)
